version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Plugins/player-tracker-ja-nhz.user.js:/usr/share/nginx/html/player-tracker-ja-nhz.user.js